### ISSUE TITLE
+1 for Linux support!

### ISSUE THREAD

**Issue by revast** [jing-interactive/MeshViewer#2]
As I cannot find an adequate viewer for glTF2 on linux, which not is a webbrowser, I would like to add my support for doing this.

**Comment by vinjn** [comment]
Thx, your help is more than welcomed. I don't use platform-dependent codes, so won't be hard to support Linux.

**Comment by revast** [comment]
I am gonna try to build it, sorry, I was not able to do so till now.

**Comment by vinjn** [comment]
Yes, you need Cinder
